<?php

function prd($var) {
  pr($var);
  die();
}

function pr($var) {
  if (is_array($var) || is_object($var)) {
    echo '<pre>' . print_r($var, true) . '</pre>';
  }
  else {
    var_dump($var);
  }
  $_ = array_reverse(debug_backtrace());

  while($d = array_pop($_)) {
    if ((strpos(@$d['file'], 'jsbalsera') === FALSE)) {
      break;
    }
  }
  echo '<br />';

  if (!empty($d['file'])) {
    echo '<br />Called from <code>' . $d['file'] . '</code>,
        line <code>' . $d['line'] .' </code></span>';
  }
}

function prq($query) {
  $conditions = $query->conditions();

  $query = (string)$query;
  $query = str_replace('{', '', $query);
  $query = str_replace('}', '', $query);

  unset($conditions['#conjunction']);

  for ($i = 0, $j = count($conditions); $i < $j; $i++) {
    $query = str_replace(':db_condition_placeholder_' . $i, $conditions[$i]['value'], $query);
  }

  prd($query);
}

/**
 * return an array with all the fields that are not an array
 * @author Jesús Sánchez Balsera <jsbalsera@gmail.com>
 * @return string physical directory where Drupal is installed
 */
function _helper_get_base_dir() {
  return (str_replace('//', '/', $_SERVER['DOCUMENT_ROOT'] . base_path()));
}

/**
 * return an array with all the fields that are not an array
 * @author Jesús Sánchez Balsera <jsbalsera@gmail.com>
 * @param type $array
 * @return array without subarrays
 */
function _helper_extract_array_leafs($param) {
  $result = array();
  if (is_array($param)) {
    foreach ($param as $k => $v) {
      $result = array_merge($result, helper_extract_array_leafs($v));
    }
  } else {
    $result[] = $param;
  }

  return $result;
}

function jsbalsera_menu() {
  $items = array();
  $items['jsbalsera/test'] = array(
    'title' => 'Dummy',
    'page callback' => '_jsbalsera_text',
    'description' => 'Testing function.',
    'access callback' => TRUE,
  );

  return $items;
}

function _jsbalsera_text() {

  echo 'Dummy menu entrance for testing';
}
